ARE-23990 - feat(license): add license event entity types
ArrowSphere/nodejs-api-client pull request #151
Opened 2023-03-14 08:22 UTC by beInDev

2023-03-14 10:12 UTC, fdianoux approved these changes

2023-03-14 14:58 UTC, fdianoux commented
Add a changelog for the version 3.22.0, change package.json version to 3.22.0-rc.1 and change branch destination to next, please

2023-03-14 14:59 UTC, fdianoux requested changes
Add a changelog for the version 3.22.0, change package.json version to 3.22.0-rc.1 and change branch destination to next, please

2023-03-15 10:23 UTC, beInDev commented
@fdianoux done!

2023-03-15 10:34 UTC, fdianoux approved these changes

2023-03-15 12:49 UTC, merged