handle several stages of filters for licenses
ArrowSphere/nodejs-api-client pull request #329
Opened 2023-10-06 16:33 UTC by ZouhourArrow

2023-10-20 15:55 UTC, sabirab2 requested changes

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/entities/license/licenseFindResult.ts
> +    | undefined;
You can just do:  ` [LicenseFindResultFields.COLUMN_SECURITY]?: SecurityFindResultDataKeywords`  the '?' indicates that the parameter is optional (could be undefined)

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/entities/license/licenseFindResult.ts
> +  [LicenseFindResultFields.COLUMN_SECURITY]?:
Same here:  ` [LicenseFindResultFields.COLUMN_SECURITY]?: SecurityFindResultDataSortParameters`

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/entities/license/licenseFindResult.ts
> +    | SecurityFindResultDataFiltersParameters
Same here:  ` [LicenseFindResultFields.COLUMN_SECURITY]?: SecurityFindResultDataFiltersParameters`

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/entities/license/licenseFindResult.ts
> +        ] ?? null,
```suggestion
        ],
```

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/entities/license/securityFindResult.ts
> +  readonly #activeFraudEvents: number | null | undefined;
```suggestion
  readonly #activeFraudEvents?: number | null;
```

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/licensesClient.ts
> +    keyParent: string,
Create a new type `KeyParent`:
```ts
type KeyParent = 'license' | 'offer';
```
```suggestion
    keyParent: KeyParent,
```

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/licensesClient.ts
> +        keyParent === 'license' ? parameters.license : parameters.offer;
```suggestion
        parameters[keyParent];
```

2023-10-20 15:55 UTC, sabirab2 commented on src/licenses/licensesClient.ts
> +      appropriateParameters !== null && appropriateParameters !== void 0
```suggestion
      appropriateParameters !== null && appropriateParameters !== undefined
```

2023-10-23 12:23 UTC, fdianoux commented
Remove the package-lock.json file please

2023-10-30 11:16 UTC, merged